# Generated by Django 3.2.9 on 2022-03-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('lng', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('activity_name', models.CharField(max_length=100)),
                ('user_count', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
