# Generated by Django 3.2.9 on 2022-03-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_location',
            name='locations_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='map_location',
            name='activity_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='map_location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='map_location',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True),
        ),
    ]
