# Generated by Django 3.2.9 on 2022-03-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20220315_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_location',
            name='activity_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='map_location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='map_location',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True),
        ),
    ]
