# Generated by Django 3.2.9 on 2022-03-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20220315_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='map_location',
            name='lng',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
