# Generated by Django 3.2.9 on 2022-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_alter_map_location_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_location',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=8),
        ),
    ]
