# Generated by Django 3.2.9 on 2022-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_alter_map_location_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_location',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
    ]
