# Generated by Django 3.2.9 on 2021-11-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sername', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('types', models.CharField(max_length=1)),
                ('idservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contain', to='services.category')),
            ],
        ),
    ]
