# Generated by Django 3.2.9 on 2021-11-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pername', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=20)),
                ('mothername', models.CharField(blank=True, max_length=100)),
                ('idnumber', models.PositiveIntegerField(default=0)),
                ('familyumber', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('education', models.CharField(max_length=90)),
                ('barcode', models.IntegerField(default=0)),
                ('blod', models.CharField(max_length=90)),
                ('helth', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.person')),
            ],
        ),
    ]
