# Generated by Django 3.2.9 on 2021-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_family_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='childcountfmale',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='family',
            name='childcountmale',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='family',
            name='elderliness',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='family',
            name='trestles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
