# Generated by Django 3.2.9 on 2022-01-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20220108_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(blank=True, choices=[('Relief', 'Relief'), ('Social support', 'Social support'), ('Health care', 'Health care')], default=None, max_length=30),
        ),
    ]
