# Generated by Django 3.2.9 on 2022-01-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_services_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='idservice',
        ),
    ]
