# Generated by Django 3.2.9 on 2022-01-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_services_idservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blod',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=None, max_length=90),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('fmale', 'أنثى'), ('male', 'ذكر')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(blank=True, choices=[('Relief', 'الاغاثة'), ('Social support', 'الدعم الاجتماعي'), ('Health care', 'الرعاية الصحية')], default=None, max_length=30),
        ),
    ]
