# Generated by Django 3.2.9 on 2022-01-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20220108_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avaregeincom',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='barcode',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='blod',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=None, max_length=90),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(blank=True, default=None, max_length=90),
        ),
        migrations.AlterField(
            model_name='person',
            name='familyumber',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='helth',
            field=models.CharField(blank=True, default=None, max_length=90),
        ),
        migrations.AlterField(
            model_name='person',
            name='incometype',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='sheltercondition',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='socialstatus',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
