# Generated by Django 3.2.9 on 2022-02-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20220108_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='updated',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='pername',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
