# Generated by Django 3.2.9 on 2022-02-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20220225_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField(max_length=3000)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(null=True, upload_to='photo/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'الأعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
