# Generated by Django 3.2.9 on 2022-03-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('fmale', 'أنثى'), ('male', 'ذكر')], default=None, max_length=5, null=True),
        ),
    ]
