# Generated by Django 3.2.9 on 2022-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_person_amount_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='number_person',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='number_person',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='positions',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(blank=True, choices=[('Relief', 'الاغاثة'), ('Social support', 'الدعم الاجتماعي'), ('Health care', 'المشفى')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='services',
            name='types',
            field=models.CharField(max_length=2),
        ),
    ]
