# Generated by Django 3.2.9 on 2022-03-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20220322_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.RemoveField(
            model_name='position',
            name='contact',
        ),
        migrations.DeleteModel(
            name='content_serv',
        ),
        migrations.DeleteModel(
            name='position',
        ),
    ]
