# Generated by Django 3.2.9 on 2022-03-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_services_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='childcountfmale',
        ),
        migrations.RemoveField(
            model_name='family',
            name='childcountmale',
        ),
        migrations.AddField(
            model_name='family',
            name='num_fmale',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='num_male',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='elderliness',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='trestles',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
