# Generated by Django 3.2.9 on 2022-03-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20220324_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='family',
            new_name='family_id',
        ),
    ]
