# Generated by Django 3.2.9 on 2022-03-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_rename_family_family_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='c',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
