# Generated by Django 3.2.9 on 2022-03-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_auto_20220324_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='family',
            new_name='ffamily',
        ),
    ]
