# Generated by Django 3.2.9 on 2022-03-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_rename_family_ffamily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ffamily',
            name='c',
        ),
        migrations.AlterField(
            model_name='ffamily',
            name='elderliness',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ffamily',
            name='num_fmale',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ffamily',
            name='num_male',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ffamily',
            name='trestles',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
