# Generated by Django 3.2.9 on 2022-03-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_auto_20220324_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'تواصل مع المستفيد', 'verbose_name_plural': 'تواصل'},
        ),
        migrations.AlterModelOptions(
            name='ffamily',
            options={'verbose_name': 'عائلةالمستفيد', 'verbose_name_plural': 'عائلات المستفيدين'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'الطلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'المستفيد', 'verbose_name_plural': 'المستفيدين'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'الخدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AddField(
            model_name='person',
            name='isseen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job',
            field=models.CharField(max_length=100, verbose_name='العمل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job2',
            field=models.CharField(blank=True, max_length=100, verbose_name='عمل أخر'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='personcontact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.person', verbose_name='اسم المستفيد'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='placejob',
            field=models.CharField(max_length=100, verbose_name='مكان العمل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tele',
            field=models.IntegerField(default=0, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='ffamily',
            name='elderliness',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='عدد الكهول'),
        ),
        migrations.AlterField(
            model_name='ffamily',
            name='family_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.person', verbose_name='اسم الشخص'),
        ),
        migrations.AlterField(
            model_name='ffamily',
            name='num_fmale',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='عدد الإناث'),
        ),
        migrations.AlterField(
            model_name='ffamily',
            name='num_male',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='عدد الذكور'),
        ),
        migrations.AlterField(
            model_name='ffamily',
            name='trestles',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='عدد الحوامل'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='idperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='services.person', verbose_name='اسم المستفيد'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='idserv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='services.services', verbose_name='اسم الخدمة'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number_person',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status_order',
            field=models.CharField(max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(blank=True, choices=[('Relief', 'الاغاثة'), ('Social support', 'الدعم الاجتماعي'), ('Health care', 'المشفى')], default=None, max_length=30, verbose_name='تصينف الخدمة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='contact',
            field=models.ManyToManyField(through='services.orders', to='services.person', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='number_person',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='services',
            name='positions',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='مكان الخدمة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sername',
            field=models.CharField(max_length=100, verbose_name='اسم الخدمة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.BooleanField(verbose_name='حالة الخدمة'),
        ),
        migrations.AlterField(
            model_name='services',
            name='types',
            field=models.CharField(max_length=2, verbose_name='نمط'),
        ),
    ]
