# Generated by Django 3.2.9 on 2022-03-26 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_auto_20220326_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sendemail',
            field=models.BooleanField(default=False, verbose_name='ارسال رسالة '),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
