# Generated by Django 3.2.9 on 2022-03-29 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0033_auto_20220326_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='isseen',
            field=models.BooleanField(default=False, verbose_name='تمت مشاهدته'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pername',
            field=models.CharField(default=None, max_length=20, verbose_name='الاسم الكامل'),
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_detail', models.TextField()),
                ('status', models.BooleanField()),
                ('read_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
