# Generated by Django 3.2.9 on 2022-03-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_auto_20220329_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify',
            old_name='read_by',
            new_name='read_by_user',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='status',
        ),
    ]
