# Generated by Django 3.2.9 on 2022-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_notif_addnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif_addnew',
            name='isread',
            field=models.BooleanField(default=False),
        ),
    ]
