# Generated by Django 3.2.9 on 2022-04-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_alter_notif_addnew_isread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notif_addnew',
        ),
    ]
