# Generated by Django 3.2.9 on 2022-04-11 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_delete_notif_addnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='notif_addnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isread', models.BooleanField(default=False)),
                ('ord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.orders')),
            ],
        ),
    ]
