# Generated by Django 3.2.9 on 2022-04-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_notif_addnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif_addnew',
            name='ord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.person'),
        ),
    ]
