# Generated by Django 3.2.9 on 2022-04-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_alter_notif_addnew_ord'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='imgbarcode',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
